### ISSUE TITLE
Team Listing Page

### ISSUE THREAD

**Issue by rcaracaus** [rcaracaus/desarol#138]
Acceptance Criteria: 

- No detail pages, just listing.
- Team member image, first and last name, role
- Team link should be in main menu

**Comment by rcaracaus** [comment]
We just need a listing with references to images in a separate /team markdown file, this ticket doesn't add images to blogs or anything, just gets team listing working.

Avatar, name, title, description

We also need "team" in the main menu

**Comment by edisch** [comment]
- [ ] needs to look more like [fourkitchens](https://www.fourkitchens.com/team/) with every team member visible straight away
