### ISSUE TITLE
Blog listing on homepage

### ISSUE THREAD

**Issue by rcaracaus** [rcaracaus/desarol#148]
We only need to list 3 blogs

**Comment by rcaracaus** [comment]
Remove services

**Comment by edisch** [comment]
- [ ] needs to be ordered by date
- [ ] needs author photo
- [ ] needs author block

**Comment by edisch** [comment]
![screen shot 2016-12-01 at 10 24 04 am](https://cloud.githubusercontent.com/assets/1893118/20802058/665ce6d8-b7b0-11e6-93e7-d11dd71bb8c8.png)

**Comment by edisch** [comment]
![screen shot 2016-12-01 at 10 32 34 am](https://cloud.githubusercontent.com/assets/1893118/20802389/80779418-b7b1-11e6-98ea-5a3b3f07294c.png)

More like this than Mediums, use the same typography as the blog detail page
