### ISSUE TITLE
Global Typography

### ISSUE THREAD

**Issue by edisch** [rcaracaus/desarol#177]
Acceptance criteria:
1) All fonts on the site should be consistent
2) We should remove  "papyrus" font and replace with something more techy
3) Line heighst should be closer together, easier to read.
4) Possibly look into new fonts only if they looks really good

**Comment by edisch** [comment]
![screen shot 2016-12-06 at 11 54 59 am](https://cloud.githubusercontent.com/assets/1893118/20940020/d1aa8616-bbb6-11e6-93a6-ac88c49f5003.png)

This is the "papyrus" font we hate

**Comment by astolfivincent** [comment]
![screen shot 2016-12-07 at 9 33 04 am](https://cloud.githubusercontent.com/assets/2312432/20979093/420e044c-bc60-11e6-832e-c0fea05b53cf.png)

Here's what Lato looks like at weight 500
